//! Repositories for webhook subscriptions and the delivery outbox.
//!
//! Two tables (see migration 009):
//! * `webhook_subscriptions` — registered callback URLs with optional
//!   route/asset/status filters.
//! * `webhook_deliveries` — the durable outbox. Enqueued by the store writer,
//!   drained by the dispatch loop; rows survive a crash/restart so no delivery
//!   is silently lost.

use chrono::{DateTime, Utc};
use serde::Serialize;
use serde_json::Value as JsonValue;
use sqlx::{FromRow, PgPool};
use uuid::Uuid;

use strait_core::error::{Result, StraitError};

use crate::db::Database;

/// A registered webhook subscription.
#[derive(Debug, Clone, FromRow, Serialize)]
pub struct WebhookSubscriptionRow {
    pub id: Uuid,
    pub url: String,
    /// HMAC-SHA256 key for payload signatures. Never expose in API responses
    /// after creation.
    #[serde(skip_serializing)]
    pub signing_secret: String,
    /// Token required to GET/DELETE this subscription. Never expose after creation.
    #[serde(skip_serializing)]
    pub management_token: String,
    /// NULL/empty = match every route/asset/status on that dimension.
    pub routes: Option<Vec<String>>,
    pub assets: Option<Vec<String>>,
    pub statuses: Option<Vec<String>>,
    pub active: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Parameters for registering a subscription. Secrets are generated by the
/// caller (strait-api) so this crate stays free of crypto/rand concerns.
#[derive(Debug, Clone)]
pub struct CreateWebhookSubscription {
    pub url: String,
    pub signing_secret: String,
    pub management_token: String,
    pub routes: Option<Vec<String>>,
    pub assets: Option<Vec<String>>,
    pub statuses: Option<Vec<String>>,
}

/// One outbox row awaiting (or having finished) delivery.
#[derive(Debug, Clone, FromRow, Serialize)]
pub struct WebhookDeliveryRow {
    pub id: Uuid,
    pub subscription_id: Uuid,
    pub transfer_id: Uuid,
    pub event_type: String,
    pub payload: JsonValue,
    pub status: String,
    pub attempt_count: i32,
    pub next_attempt_at: DateTime<Utc>,
    pub last_error: Option<String>,
    /// Round-trip time of the most recent POST attempt, in milliseconds.
    pub response_ms: Option<i32>,
    pub delivered_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

/// A due delivery joined with its subscription's URL + signing secret, as the
/// dispatch loop needs both to POST.
#[derive(Debug, Clone, FromRow)]
pub struct DueDelivery {
    pub id: Uuid,
    pub subscription_id: Uuid,
    pub event_type: String,
    pub payload: JsonValue,
    pub attempt_count: i32,
    pub url: String,
    pub signing_secret: String,
}

/// Repository over `webhook_subscriptions` and `webhook_deliveries`.
pub struct WebhookRepo<'a> {
    pool: &'a PgPool,
}

impl<'a> WebhookRepo<'a> {
    pub fn new(db: &'a Database) -> Self {
        Self { pool: db.pool() }
    }

    // ── Subscriptions ─────────────────────────────────────────────────────────

    /// Register a new subscription and return the stored row.
    pub async fn create(&self, params: CreateWebhookSubscription) -> Result<WebhookSubscriptionRow> {
        let row = sqlx::query_as::<_, WebhookSubscriptionRow>(
            "INSERT INTO webhook_subscriptions
                (id, url, signing_secret, management_token, routes, assets, statuses)
             VALUES ($1, $2, $3, $4, $5, $6, $7)
             RETURNING *",
        )
        .bind(Uuid::new_v4())
        .bind(&params.url)
        .bind(&params.signing_secret)
        .bind(&params.management_token)
        .bind(&params.routes)
        .bind(&params.assets)
        .bind(&params.statuses)
        .fetch_one(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(row)
    }

    /// Fetch a subscription only if the presented management token matches.
    /// Returns `None` for unknown id *or* wrong token — callers should treat
    /// both identically (404) to avoid confirming which ids exist.
    pub async fn get_by_id_and_token(
        &self,
        id: Uuid,
        management_token: &str,
    ) -> Result<Option<WebhookSubscriptionRow>> {
        let row = sqlx::query_as::<_, WebhookSubscriptionRow>(
            "SELECT * FROM webhook_subscriptions WHERE id = $1 AND management_token = $2",
        )
        .bind(id)
        .bind(management_token)
        .fetch_optional(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(row)
    }

    /// Delete a subscription (token-gated, same non-disclosure semantics as
    /// `get_by_id_and_token`). Returns whether a row was removed. Pending
    /// deliveries go with it via ON DELETE CASCADE.
    pub async fn delete(&self, id: Uuid, management_token: &str) -> Result<bool> {
        let res = sqlx::query(
            "DELETE FROM webhook_subscriptions WHERE id = $1 AND management_token = $2",
        )
        .bind(id)
        .bind(management_token)
        .execute(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(res.rows_affected() > 0)
    }

    /// Active subscriptions whose filters match the given transfer dimensions.
    /// A NULL or empty filter array matches everything on that dimension.
    pub async fn active_matching(
        &self,
        route: &str,
        asset: &str,
        status: &str,
    ) -> Result<Vec<WebhookSubscriptionRow>> {
        let rows = sqlx::query_as::<_, WebhookSubscriptionRow>(
            "SELECT * FROM webhook_subscriptions
             WHERE active
               AND (routes   IS NULL OR cardinality(routes)   = 0 OR $1 = ANY(routes))
               AND (assets   IS NULL OR cardinality(assets)   = 0 OR $2 = ANY(assets))
               AND (statuses IS NULL OR cardinality(statuses) = 0 OR $3 = ANY(statuses))",
        )
        .bind(route)
        .bind(asset)
        .bind(status)
        .fetch_all(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(rows)
    }

    // ── Deliveries (outbox) ───────────────────────────────────────────────────

    /// Enqueue one PENDING delivery for a subscription.
    pub async fn enqueue_delivery(
        &self,
        subscription_id: Uuid,
        transfer_id: Uuid,
        event_type: &str,
        payload: &JsonValue,
    ) -> Result<Uuid> {
        let id = Uuid::new_v4();
        sqlx::query(
            "INSERT INTO webhook_deliveries (id, subscription_id, transfer_id, event_type, payload)
             VALUES ($1, $2, $3, $4, $5)",
        )
        .bind(id)
        .bind(subscription_id)
        .bind(transfer_id)
        .bind(event_type)
        .bind(payload)
        .execute(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(id)
    }

    /// Atomically claim up to `limit` due PENDING deliveries, joined with their
    /// subscription's URL and signing secret.
    ///
    /// Claiming pushes `next_attempt_at` forward by a short lease so a second
    /// dispatcher instance (or the next poll tick) won't pick the same rows up
    /// mid-delivery; `FOR UPDATE SKIP LOCKED` in the inner select keeps
    /// concurrent claimers from blocking each other. If the process dies
    /// mid-delivery the lease simply expires and the row comes due again —
    /// nothing is lost (deliveries may then repeat: consumers must treat them
    /// as at-least-once).
    pub async fn claim_due_deliveries(&self, limit: i64) -> Result<Vec<DueDelivery>> {
        let rows = sqlx::query_as::<_, DueDelivery>(
            "UPDATE webhook_deliveries d
             SET next_attempt_at = NOW() + INTERVAL '2 minutes'
             FROM webhook_subscriptions s
             WHERE d.id IN (
                 SELECT id FROM webhook_deliveries
                 WHERE status = 'PENDING' AND next_attempt_at <= NOW()
                 ORDER BY next_attempt_at ASC
                 LIMIT $1
                 FOR UPDATE SKIP LOCKED
             )
               AND s.id = d.subscription_id
               AND s.active
             RETURNING d.id, d.subscription_id, d.event_type, d.payload, d.attempt_count,
                       s.url, s.signing_secret",
        )
        .bind(limit)
        .fetch_all(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(rows)
    }

    /// Mark a delivery as successfully delivered.
    pub async fn mark_delivered(&self, id: Uuid, response_ms: Option<i32>) -> Result<()> {
        sqlx::query(
            "UPDATE webhook_deliveries
             SET status = 'DELIVERED', delivered_at = NOW(), last_error = NULL,
                 attempt_count = attempt_count + 1, response_ms = $2
             WHERE id = $1",
        )
        .bind(id)
        .bind(response_ms)
        .execute(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(())
    }

    /// Record a failed attempt and schedule the next one.
    pub async fn mark_retry(
        &self,
        id: Uuid,
        error: &str,
        next_attempt_at: DateTime<Utc>,
        response_ms: Option<i32>,
    ) -> Result<()> {
        sqlx::query(
            "UPDATE webhook_deliveries
             SET attempt_count = attempt_count + 1, last_error = $2, next_attempt_at = $3,
                 response_ms = $4
             WHERE id = $1",
        )
        .bind(id)
        .bind(error)
        .bind(next_attempt_at)
        .bind(response_ms)
        .execute(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(())
    }

    /// Give up on a delivery permanently (attempt budget exhausted).
    pub async fn mark_failed_permanently(
        &self,
        id: Uuid,
        error: &str,
        response_ms: Option<i32>,
    ) -> Result<()> {
        sqlx::query(
            "UPDATE webhook_deliveries
             SET status = 'FAILED', attempt_count = attempt_count + 1, last_error = $2,
                 response_ms = $3
             WHERE id = $1",
        )
        .bind(id)
        .bind(error)
        .bind(response_ms)
        .execute(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(())
    }

    /// Most recent deliveries for one subscription (newest first) — backs the
    /// manage UI's attempt history. Token-checking is the caller's job (the
    /// HTTP handler verifies via `get_by_id_and_token` first).
    pub async fn recent_deliveries(
        &self,
        subscription_id: Uuid,
        limit: i64,
    ) -> Result<Vec<WebhookDeliveryRow>> {
        let rows = sqlx::query_as::<_, WebhookDeliveryRow>(
            "SELECT * FROM webhook_deliveries
             WHERE subscription_id = $1
             ORDER BY created_at DESC
             LIMIT $2",
        )
        .bind(subscription_id)
        .bind(limit)
        .fetch_all(self.pool)
        .await
        .map_err(StraitError::Database)?;
        Ok(rows)
    }
}
